In [7]:
import pandas as pd
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [8]:
# Load data
data = pd.read_csv("student_habits_performance.csv", index_col = "student_id")
data

,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
student_id,,,,,,,,,,,,,,,
S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [10]:
# Check for na values
print(data.isna().sum())

age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [14]:
# View how NA data is stored
print(data[data["parental_education_level"].isna()])

            age  gender  study_hours_per_day  social_media_hours  \
student_id
S1010        19  Female                  4.6                 3.7
S1033        18  Female                  4.0                 0.9
S1047        23  Female                  2.5                 2.9
S1074        21  Female                  2.3                 1.0
S1093        22    Male                  4.1                 2.5
...         ...     ...                  ...                 ...
S1921        23  Female                  4.4                 2.7
S1925        19   Other                  1.7                 2.9
S1939        18  Female                  4.7                 3.2
S1945        23    Male                  6.0                 2.9
S1967        22    Male                  5.2                 4.1

            netflix_hours part_time_job  attendance_percentage  sleep_hours  \
student_id
S1010                 0.8            No                   77.6          5.8
S1033                 1.1            No                   99.5          5.8
S1047                 2.7            No                   83.5          7.0
S1074                 0.4            No                  100.0          6.4
S1093                 3.0            No                   85.1          5.8
...                   ...           ...                    ...          ...
S1921                 1.0            No                   79.8          6.1
S1925                 1.6           Yes                   97.3          8.7
S1939                 1.9            No                   75.2          5.4
S1945                 2.1           Yes                   98.9          6.4
S1967                 3.8            No                   95.6          5.9

           diet_quality  exercise_frequency parental_education_level  \
student_id
S1010              Fair                   1                      NaN
S1033              Poor                   2                      NaN
S1047              Good                   4                      NaN
S1074              Fair                   6                      NaN
S1093              Good                   4                      NaN
...                 ...                 ...                      ...
S1921              Fair                   6                      NaN
S1925              Good                   1                      NaN
S1939              Good                   3                      NaN
S1945              Poor                   0                      NaN
S1967              Fair                   0                      NaN

           internet_quality  mental_health_rating  \
student_id
S1010                  Good                     3
S1033               Average                     5
S1047                  Good                     8
S1074                  Good                     1
S1093                  Good                     5
...                     ...                   ...
S1921               Average                     3
S1925                  Good                     7
S1939                  Good                     6
S1945               Average                     7
S1967                  Good                     6

           extracurricular_participation  exam_score
student_id
S1010                                 No        63.3
S1033                                 No        70.7
S1047                                Yes        59.7
S1074                                 No        66.9
S1093                                 No        70.2
...                                  ...         ...
S1921                                 No        85.4
S1925                                 No        53.6
S1939                                 No        71.0
S1945                                 No       100.0
S1967                                 No        76.1

[91 rows x 15 columns]